### ISSUE TITLE
Bottom camera casing doesn't match pictures

### ISSUE THREAD

**Issue by texruska** [xpDIY/3DPlacer#10]
Looks like the bottom camera casing file is out of date

Expected (from shop page):

![bottomCamera_v0 9](https://github.com/xpDIY/3DPlacer/assets/2800058/de1e2ffa-4aa2-4518-8397-4e4816d0728d)

Actual (after downloading):

![image](https://github.com/xpDIY/3DPlacer/assets/2800058/49b30dc9-b800-476f-ad35-dcf91fd8b425)

You can see that there's nowhere for the camera cover to clip into

I would also double check the camera cover, too, just in case

**Comment by xpDIY** [comment]
Thanks for feedback, this has been updated, could you get the latest version of download and give it a try?

**Comment by texruska** [comment]
Thanks, that's all good now

I've also noticed that the nozzle head frame (Juki) is a different file to expected (notice where the top camera cover would go):

![image](https://github.com/xpDIY/3DPlacer/assets/2800058/d8799574-3d5e-45ed-b4af-028120566e71)

![image](https://github.com/xpDIY/3DPlacer/assets/2800058/f9d5ddf4-b7cc-40e5-9cea-77315e2424b8)

Can you tell that I'm in the process of building this? :)

**Comment by xpDIY** [comment]
For this one, you can use the nozzleHeadFrame.stl included in the bundle, that one is the latest version, I should probably removed the old ones. Thanks for commenting!

**Comment by texruska** [comment]
In that case issue closed 😎 I didn't even think to open the non-Juki file
