### ISSUE TITLE
Top camera fitment into nozzle frame

### ISSUE THREAD

**Issue by texruska** [xpDIY/3DPlacer#11]
As discussed I printed the non-Juki nozzle head frame, but unfortunately the PCB for my top camera is too thick to slide in place (1.6mm):

![Photo 24-11-2023, 08 37 12](https://github.com/xpDIY/3DPlacer/assets/2800058/2f5f1b40-4fae-4918-ac15-f9529afcbec1)

Is it a tolerance issue on my side? I notice that the slot is wider than the PCB (PCB is 30mm wide)

**Comment by xpDIY** [comment]
Hmm.. Ok, my camera board is thinner than what you have, I can make a
version with bigger slot width. But currently I am outside travelling, can
only do it tomorrow if that is ok.

**Comment by xpDIY** [comment]
For 30mm width, can you print a calibration cube and check, just to be
sure. I leave around 0.6mm each side to hold the camera. I will be able to
help you tomorrow when I get back.

**Comment by texruska** [comment]
That's okay. This is the 64deg OV3660 FYI, 30mmx25mm -- so the only difference is that it's thicker than yours (it fits in the bottom camera mount perfectly)

I think the width is okay if it's intentionally 1.2mm oversided, if I push it all the way to the side (like in the pic) then of course it won't sit in the other slot since they're the same depth

**Comment by xpDIY** [comment]
Now I have updated the nozzle head frame to support 1.6mm top camera (with 0.2mm tolerance, so actually height is 1.8mm), you can download the full bundle and then find the updated head frame.

**Comment by texruska** [comment]
Fits well, thanks :)
