### ISSUE TITLE
Ender 3 v2 nozzle head adapter clash

### ISSUE THREAD

**Issue by 0xBERNDOG** [xpDIY/3DPlacer#12]
It's not easy to show this, but the nozzle head adapter clashes with my gantry, causing the screw holes to not properly align

Misaligned bottom screw hole, excuse the shadows:
![Photo 29-11-2023, 00 48 28](https://github.com/xpDIY/3DPlacer/assets/2800058/1d5b13d4-a967-4d2b-b38d-f600bb5897ae)

The clash:
![Photo 29-11-2023, 00 48 43](https://github.com/xpDIY/3DPlacer/assets/2800058/7ba4d649-9c5d-4afd-bbc8-f8b0fa6cd0dd)

I propose that we add a chamfer where the clash is to give some clearance while keeping it easily printable, I only need about 1-2mm more space

**Comment by xpDIY** [comment]
Thanks for the idea, I have updated the product to include the chamfer, you can find it in https://www.xpdiy.io/product/nozzle-head-adapter-for-ender3v2-design-file/

**Comment by 0xBERNDOG** [comment]
Successful fix :)
