### ISSUE TITLE
Ender 3 v2 failing to hit homing switch

### ISSUE THREAD

**Issue by 0xBERNDOG** [xpDIY/3DPlacer#14]
It's hard to photograph this one, but my ender 3 v2 is missing the x-axis homing switch. I assume that the nozzle head adapter is supposed to hit it?

![Photo 29-11-2023, 18 20 42](https://github.com/xpDIY/3DPlacer/assets/2800058/d13041c5-1ed8-48bf-a3c1-8ebf1fcba39b)

![Photo 29-11-2023, 18 20 52](https://github.com/xpDIY/3DPlacer/assets/2800058/a89d3c93-80d6-4ceb-8eca-63089a9b9de1)

https://github.com/xpDIY/3DPlacer/assets/2800058/c9a0d3c2-87af-47b3-b61b-e6c95d8a9659

**Comment by 0xBERNDOG** [comment]
I think either a chamfer on the adapter (so the switch can be triggered by the metal bracket), or extend the adapter so that the adapter triggers the switch

At the moment the adapter clashes with the body of the switch while missing the lever

**Comment by xpDIY** [comment]
Ok, it seems like the adapter hitting the x axis stop body, I think
the switch was supposed to hit the metal part, but somehow the adapter hit
it first. Let me make a chamfer for the adapter.
In the meantime, you can bend the thin metal piece of the homing switch to
make it stick a bit out so it hits the metal first.

I will make an adaption and upload.

**Comment by xpDIY** [comment]
The new version has been uploaded, a chamfer is added. Also the home position extender I have put in an extra one with narrower gap so that it can adapt to different tolerance.

BTW, good to see you have the main components setup :)

**Comment by 0xBERNDOG** [comment]
Thanks, will print them both and update you

Except for these small issues, it's been a smooth process so far. I had been putting it off for ages

**Comment by 0xBERNDOG** [comment]
Fixed, and the homing extension fits snugly now
