### ISSUE TITLE
LED channels not wide enough

### ISSUE THREAD

**Issue by 0xBERNDOG** [xpDIY/3DPlacer#15]
In the nozzle head and bottom camera, the channel for the LEDs aren't wide enough for mine (I bought the ones from the BOM):

![Photo 05-12-2023, 10 56 49](https://github.com/xpDIY/3DPlacer/assets/2800058/269ab313-2d1e-4ef6-86a0-6309f1b0c17c)

The strip is 8mm in width

**Comment by xpDIY** [comment]
ok, I have updated the nozzle head bundle to add support for 8mm as well, you can download from the website.

**Comment by 0xBERNDOG** [comment]
Top camera fits well now, could you also adjust the bottom camera?

**Comment by xpDIY** [comment]
I have also updated the bottom camera cover, you can download and give it a try!

**Comment by 0xBERNDOG** [comment]
Looks good to me thanks
